<?php 
echo "<!DOCTYPE html>";
echo "<html>";
echo "<head>";
echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />";
echo "<meta name='viewport' content='width=device-width, initial-scale=1'>";
echo "<title>select seat</title>";
echo "<link rel='stylesheet' type='text/css' href='select_style.css' />";
echo "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>";
echo "<script>";
echo "$(document).ready(function(){:";
	echo "var count = 0;";
	echo "$('.btn').on('click',function(){";
		echo "if(count<5){";
			echo "var str = $('#selectedSeat').text();";
			echo "$('#selectedSeat').html(str + this.id);";
			echo "$(this).css('background-color','red');";
			echo "count++";
		echo "}";
	echo "});";
echo "});";
echo "</script>";
echo "</head>";
echo "<body>";
echo "<form method='post'>";
echo "<div class='a'>";
echo "<table>";
echo "<tr>";
echo "<td><input type='button' value='1'  class='btn' id='1'  /></td>";
echo "<td><input type='button' value='2'  class='btn' id='2'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='3'  class='btn' id='3'  /></td>";
echo "<td><input type='button' value='4'  class='btn' id='4'  /></td>";
echo "</tr>";

echo "<tr>";
echo "<td><input type='button' value='5'  class='btn' id='5'  /></td>";
echo "<td><input type='button' value='6'  class='btn' id='6'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='7'  class=btn id='7'  /></td>";
echo "<td><input type='button'  value='8' class=btn id='8'  /></td>";
echo "</tr>";

echo "<tr>";
echo "<td><input type='button' value='9'  class='btn' id='9'  /></td>";
echo "<td><input type='button' value='10' class='btn' id='10'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='11' class='btn' id='11'  /></td>";
echo "<td><input type='button' value='12' class='btn' id='12'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td> selected seat</td>";
echo "</tr>";

echo "<tr>";
echo "<td><input type='button' value='13'  class='btn' id='3'  /></td>";
echo "<td><input type='button' value='14'  class='btn' id='14'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='15' class='btn' id='15'  /></td>";
echo "<td><input type='button' value='16'  class='btn' id='16'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='17'  class='btn' id='17'  /></td>";
echo "<td><input type='button' value='18'  class='btn' id='18'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='19' class='btn' id='19'  /></td>";
echo "<td><input type='button' value='20'  class='btn' id='20'  /></td>";
echo "<td><input type='button' value='book' name='cmdbook' /></td></tr>";
echo "<tr>";
echo "<td><input type='button' value='21'  class='btn' id='21' /></td>";
echo "<td><input type='button' value='22'  class='btn' id='22'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='23'  class='btn' id='23'  /></td>";
echo "<td><input type='button' value='24'  class='btn' id='24'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='25'  class='btn' id='25'  /></td>";
echo "<td><input type='button' value='26'  class='btn' id='26'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='27'  class='btn' id='27'  /></td>";
echo "<td><input type='button' value='28'  class='btn' id='28'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='29'  class='btn' id='29'  /></td>";
echo "<td><input type='button' value='30'  class='btn' id='30'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='31'  class='btn' id='31'  /></td>";
echo "<td><input type='button' value='32'  class='btn' id='32'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='33'  class='btn' id='33'  /></td>";
echo "<td><input type='button' value='34'  class='btn' id='34'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='35'  class='btn' id='35'  /></td>";
echo "<td><input type='button' value='36'  class='btn' id='36'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='37'  class='btn' id='37'  /></td>";
echo "<td><input type='button' value='38'  class='btn' id='38'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='39'  class='btn' id='39' /></td>";
echo "<td><input type='button' value='40'  class='btn'id='40'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='41'  class='btn' id='41'  /></td>";
echo "<td><input type='button' value='42'  class='btn' id='42'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='43'  class='btn' id='43'  /></td>";
echo "<td><input type='button' value='44'  class='btn' id='44'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='45'  class='btn' id='45' /></td>";
echo "<td><input type='button' value='46'  class='btn' id='46'  /></td>";
echo "<td>&nbsp; </td>";
echo "<td><input type='button' value='47'  class='btn' id='47'  /></td>";
echo "<td><input type='button' value='48'  class='btn' id='btn48'  /></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='button' value='49'  class='btn' id='49'  /></td>";
echo "<td><input type='button' value='50'  class='btn' id='50'  /></td>";
echo "<td><input type='button' value='51'  class='btn' id='51'  /></td>";
echo "<td><input type='button' value='52'  class='btn' id='52'  /></td>";
echo "<td><input type='button' value='53'  class='btn' id='53'  /></td>";
echo "</tr>";
echo "</table>";
echo "<label id='selectedSeat'></label>";
echo "</form>";

echo "</body>";
echo "</html>";
?>